modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://extraspecialstudio.co.uk"
authors="${mod_authors}"
displayTest="MATCH_VERSION"
logoFile="${mod_id}.png"
description='''${mod_description}'''

[[mixins]]
config="radiotowers.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="extraspecialcore"
type="required"
versionRange="${esc_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="extraspeciallib"
type="required"
versionRange="${esl_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="esn"
type="optional"
versionRange="${esn_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dead_air"
type="optional"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tacz"
type="optional"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="berezkas_zombie_waves_api"
type="optional"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="berezka_api"
type="optional"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
